# Generated by Django 4.1.3 on 2022-12-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="image",
        ),
    ]
